# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2009 XMMS2 Team

import Options

source = """
s4.c
sourcepref.c
val.c
cond.c
log.c
index.c
result.c
resultset.c
fetchspec.c
relation.c
const.c
pattern.c
uuid.c
transaction.c
oplist.c
lock.c
""".split()

def build(bld):
    bld(features = 'c cstlib',
        target = 's4',
        source = source,
        includes = '../../include',
        uselib = 'glib2',
        export_incdirs = '../../include',
        install_path = None
        )

def configure(conf):
    return True

def options(opts):
    pass
