# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2009 XMMS2 Team

source = """
s4_bench.c
logging.c
""".split()

def build(bld):
    bld(features = "c cprogram",
        target = "s4_bench",
        source = source,
        use = "s4",
        uselib = "glib2 gthread2",
        install_path = None
        )

def configure (conf):
    return True
def options (opt):
    pass
