# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2009 XMMS2 Team

import Options

source = """
main.y
lexer.l
config.c
print.c
""".split()

def build(bld):
    bld(features='c cprogram',
        target = 's4',
        name = 's4-tool',
        source = source,
        includes = '.',
        use = "s4",
        uselib = "glib2 gthread2 readline"
        )

def configure (conf):
    conf.check_tool("flex")
    conf.check_tool("bison")
    conf.env.append_value('BISONFLAGS', '--verbose')

    rl_headers=["stdio.h", "readline/readline.h"]
    conf.check_cc(header_name=rl_headers)
    conf.check_cc(lib="readline", header_name=rl_headers, function_name='readline',
            uselib_store="readline")

def options (opt):
    pass
