# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2009 XMMS2 Team
#

def build(bld):
    obj = bld.new_task_gen('cc')
    obj.source = "strstore.c intpair.c midb.c log.c idt.c sourcepref.c".split()
    obj.includes = '.. ../../include'
    obj.target = 's4_backend'
    obj.uselib = 'glib2'

def configure(conf):
    return True

def set_options(opt):
    pass
