s4_suite = ["s4/t_set.c", "s4/t_intpair.c", "s4/t_strstore.c", "s4/t_entry.c", "s4/t_s4.c"]

def configure(conf):
    if not conf.check_cc(header_name="CUnit/CUnit.h"):
        return False
    if not conf.check_cc(lib="cunit", uselib_store="cunit"):
        return False

    code = """
           static void T (void) __attribute__ ((constructor (220)));
           static void T (void) {};
           int main() { return 0; }
    """
    if not conf.check_cc(fragment=code, msg="Checking for constructor attribute"):
        return False

    conf.check_cfg(package='valgrind', uselib_store='valgrind', args='--cflags')

    return True

def build(bld):
    obj = bld.new_task_gen('cc', 'program')
    obj.target = "test_s4"
    obj.source = ['runner/main.c', 'runner/valgrind.c'] + s4_suite
    obj.includes = '. runner/ ../src ../include'
    obj.uselib_local = 's4'
    obj.uselib = 'gthread2 cunit valgrind'
    obj.install_path = None

def set_options(o):
    pass
