from waflib import Errors

test_s4_src = """
s4/t_s4.c
s4/t_sourcepref.c
s4/t_val.c
s4/t_cond.c
s4/t_transactions.c
s4/t_pattern.c
""".split()

def configure(conf):
    conf.load("unittest", tooldir="waftools")

    conf.check_cc(header_name="CUnit/CUnit.h", mandatory=False)
    conf.check_cc(lib="cunit", uselib_store="cunit", mandatory=False)
    conf.check_cc(lib="ncurses", uselib_store="ncurses", mandatory=False)

    conf.check_cfg(package='valgrind', uselib_store='valgrind', args='--cflags', mandatory=False)

def build(bld):
    if not bld.env.HAVE_CUNIT_CUNIT_H:
        return

    bld(features = 'c cprogram test',
        target = 'test_s4',
        source = test_s4_src,
        includes = ". runner ../src ../include",
        use = "s4",
        uselib = "glib2 gthread2 cunit valgrind",
        install_path = None
        )

def options(o):
    o.load("unittest", tooldir="waftools")
